# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectZen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConnectZen

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'PhoneNumberKit', '~> 3.3'


  target 'ConnectZenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConnectZenUITests' do
    # Pods for testing
  end


end
